# action.yml
name: 'Weather GitHub Action'
description: 'Retrieve current weather data using OpenWeather'
inputs:
  lat:
    description: 'Latitude'
    required: true
    default: '44.4361414'
  lon:
    description: 'Longitude'
    required: true
    default: '26.1027202'
  api_key:
    description: 'OpenWeather API Key'
    required: true
  update_readme:
    description: 'Update README.md file with current weather'
    required: false
    default: false
outputs:
  temperature: # id of output
    description: 'Current temperature'
  condition:
    description: 'Weather condition ex cloudy'
branding:
  icon: 'cloud'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.lat }}
    - ${{ inputs.lon }}
    - ${{ inputs.api_key }}
    - ${{ inputs.update_readme }}