name: 'Workflow for weather'
on: 
    schedule:
      - cron: '0 10 * * *'
    workflow_dispatch:
    
permissions: 
  contents: write

jobs:
    weather-job:
        runs-on: ubuntu-latest
        steps:
            - name: Clone the repo
              uses: actions/checkout@v7
            - name: Custom action
              env:
                GH_TOKEN: ${{ github.token }}
              id: weather
              uses: ./
              with:
                lat: 44.4361414
                lon: 26.1027202
                api_key: ${{ secrets.OPENWEATHER_API }}
                update_readme: true
                
            - name: Show outputs
              run: echo "Temp is ${{ steps.weather.outputs.temperature }}, condition is ${{ steps.weather.outputs.condition }}"

            - name: Check README
              run: cat README.md
              
